env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - sort-exports
  - prefer-arrow
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi: off
  "@typescript-eslint/semi":
    - error
    - always
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: comma
        requireLast: false
      overrides:
        interface:
          multiline:
            delimiter: semi
            requireLast: true
  import/group-exports: error
  import/no-self-import: error
  import/no-useless-path-segments: error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - parent
        - sibling
        - index
        - object
        - type
      alphabetize:
        order: asc
  sort-imports:
    - error
    - ignoreDeclarationSort: true
  sort-exports/sort-exports:
    - error
    - sortDir: asc
  comma-dangle:
    - error
    - never
  arrow-body-style:
    - error
    - as-needed
  prefer-arrow/prefer-arrow-functions:
    - error
    - singleReturnOnly: true
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: true
  func-style:
    - error
    - expression
  brace-style:
    - error
    - 1tbs
  curly: error
  no-multi-spaces: error
  prefer-template: error
